### PR TITLE
Reformat

### PR DESCRIPTION
**Pull request by Ethan-Passino**
This should definitely be the last time we reformat everything in our project we got together as a group and made it how we would like it. Please check everything and make sure we are all good with it and if you aren't please request changes, I personally don't want to go through and have to reformat everything again.

### CODE REVIEW

**Review by white-calx — APPROVED** [review]
everything looks to be where we agreed on putting it

**Comment by Ethan-Passino** [comment]
@InfectedZomB if you could review this at some point that would be great.

**Review by InfectedZomB — APPROVED** [review]
It looks good.

**Comment by InfectedZomB** [comment]
> @InfectedZomB if you could review this at some point that would be great.

Dr Chen's email regarding my absence today is what notified me. I thought I had already responded to this days ago. Apparently not - I am genuinely unsure what caused my last comment to not post. I had mentioned the double src folder but I don't think it's that big of a deal at this point. I will do better to ensure my comments post.

**Comment by Ethan-Passino** [comment]
> > @InfectedZomB if you could review this at some point that would be great.
> 
> Dr Chen's email regarding my absence today is what notified me. I thought I had already responded to this days ago. Apparently not - I am genuinely unsure what caused my last comment to not post. I had mentioned the double src folder but I don't think it's that big of a deal at this point. I will do better to ensure my comments post.
No worries. I tried to fix the double SRC folder by changing the src folder name in the frontend for a good hour or more but changing it broke the entire project and would not let me run or build anything in the frontend. It might be possible to change the one in the root without it breaking, but im not sure if we want to do that or not.

**Comment by InfectedZomB** [comment]
If it breaks things with the way you've decided to handle it then I'd just leave it for now. The organizational structure is there - the name of the folder is a low priority refactoring task for later

**Pull request merged**
